timezone: Europe/London
encoding: UTF-8
permalink: /:title/
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
    ['.backup',
    '_drafts',
    '.idea/',
    'node_modules',
    'package-lock.json',
    'gulpfile.js',
    'package.json',
    'README.md',
    'LICENSE',
    '/img-in']

# SEO
title: Mariusz Zarzycki
description: Always open to a chat about the web, or anything else. Let's get working
url: https://vallode.com/
author: Mariusz Zarzycki
twitter:
  username: Vallode_
logo: /images/favicon.png
