timezone: Europe/London
encoding: UTF-8
permalink: /:title/
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
    ['_posts']

# SEO
title: Mariusz Zarzycki
description: Freelance web developer knowledgable both in front-end and back-end work, friendly and talkative person
url: https://vallode.cf/
author: Mariusz Zarzycki
twitter:
  username: Vallode_
logo: /images/favicon.png